### ISSUE TITLE
Icon is creepy

### ISSUE THREAD

**Issue by dmdeller** [beheadedmyway/gity#1]
It looks like it has three eyes or something. _shudder_

**Comment by RobertWHurst** [comment]
You can't be serious... I think its cool.

**Comment by evolvedwebsites** [comment]
Ha ha

**Comment by DisruptiveMind** [comment]
my first contribution so don't flame me,....yet.

How about one eye being "+" and the other "-" to make use of diff +/-'s ?

**Comment by RobertWHurst** [comment]
.. your actually serious?
Not flaming you or anything, but If you want a small detail like an icon modification you need to do it yourself. No one working on Gity has the time to make an icon right now. Maybe if more people wanted it changed then it would be a real issue, this is not, sorry.

**Comment by DisruptiveMind** [comment]
I understand,

I am serious...and it's not an issue, I am willing to contribute to the graphic side of the project, if everyone is willing.

Here are some of the samples, I suggest:

http://disruptiveart.com/playground/logos

Cheers,

DisruptiveMind

**Comment by DisruptiveMind** [comment]
I'm not sure how to contribute exactly and willing to learn how, but here is the layout: http://disruptiveart.com/playground/logos/gity_layout.jpg

**Comment by stephenallred** [comment]
I disagree with changing the icon. The existing one reflects the Git logo well (three pluses and three minuses; inverted ±±±, see http://git-scm.com/) and I would far rather have it on my dock than DisruptiveMind's version.

**Comment by DisruptiveMind** [comment]
Interesting, thanks for the feedback stephenallred

**Comment by bsneed** [comment]
not changing the icon, sorry.
