### ISSUE TITLE
In history view, every other commit doesn't show commit message or affected files

### ISSUE THREAD

**Issue by rmurphey** [beheadedmyway/gity#10]
I am in the history view of my local master branch. I click on one commit, and I see commit details as expected (http://gyazo.com/36c86845311916959e86d57a624477a7.png). I choose the next commit in the list (or the previous one), and there are no commit details (http://gyazo.com/ee498e39e868c2aa9ecd69092d8d16d3.png). This pattern repeats with every other commit in the history view. Adjusting the context slider causes the commit details to appear when they are initially missing, but then, moving to the next/previous commit, the commit details are empty again. 

OS10.6.4, Gity Version 0.3.4 (6743)

**Comment by bsneed** [comment]
I think this is fixed now.
