### ISSUE TITLE
Checkmark for Current Branch in Source View Misaligned

### ISSUE THREAD

**Issue by Mr0grog** [beheadedmyway/gity#12]
If the source view has scrollbars, the checkmark that indicates the current branch becomes misaligned from the current branch. Further, scrolling the source view causes the checkmark to move.

Screenshots:
http://skitch.com/mr0grog/dcu2h/gity-source-noscroll <-- The source view without scrollbars; looks fine.
http://skitch.com/mr0grog/dcu27/gity-source-scrollbars <-- The same source view with remote branches expanded to cause scrollbars. The checkmark is now aligned with the wrong branch.
http://skitch.com/mr0grog/dcu3y/git-source-scrolling <-- Same as above, but scrolled down a bit. The checkmark is now aligned with a different branch.

**Comment by bsneed** [comment]
This appears to have been fixed already.
