### ISSUE TITLE
Build fails - /gity/English.lproj/GittyDocument.xib:0:0 Unable to resolve plug-in dependency for "GittyDocument.xib".  

### ISSUE THREAD

**Issue by DataZombies** [beheadedmyway/gity#19]
CompileXIB English.lproj/GittyDocument.xib
cd /Users/djpinter/Documents/gity
/Developer/usr/bin/ibtool --errors --warnings --notices --output-format human-readable-text --compile /Users/djpinter/Documents/gity/build/Release/Gity.app/Contents/Resources/English.lproj/GittyDocument.nib /Users/djpinter/Documents/gity/English.lproj/GittyDocument.xib --sdk /Developer/SDKs/MacOSX10.6.sdk

/\* com.apple.ibtool.errors */
/Users/djpinter/Documents/gity/English.lproj/GittyDocument.xib: error: Unable to resolve plug-in dependency for "GittyDocument.xib".
    Recovery Suggestion: Locate the com.brandonwalkin.BWToolkit Interface Builder plug-in to continue opening this document. Consider using the --plugin option or Interface Builder's plug-in preferences to resolve this dependency.
    Underlying Errors:
        Description: Could not load plug-in.
        Failure Reason: Could not determine the location of the plug-in with the identifier com.brandonwalkin.BWToolkit

**Comment by beheadedmyway** [comment]
install the BWToolkit plugin in the plugins folder.

**Comment by DataZombies** [comment]
Moved ~/Documents/gity/plugins/BWToolkitForSnowLeopard.ibplugin into ~/Library/Plug-ins/BWToolkitForSnowLeopard.ibplugin, tried to build the project and get the same error.

**Comment by beheadedmyway** [comment]
that's probably not the right place to put it. install the plugin through interface builder (in preferences). or just double click the plugin.. interface builder will handle it.

**Comment by DataZombies** [comment]
That worked. Thanks.
