### ISSUE TITLE
Builds

### ISSUE THREAD

**Issue by lmartins** [beheadedmyway/gity#21]
would be nice if this could be made available already built, for those who dont know how to it.

**Comment by beheadedmyway** [comment]
ok. I can get gityapp.com back up and running.

**Comment by beheadedmyway** [comment]
gityapp.com is back and running. got a build up.

**Comment by lmartins** [comment]
This is great, thanks. =)

**Comment by texastoland** [comment]
Is `gityapp.com` down temporarily?
