### ISSUE TITLE
Solving a conflicted state

### ISSUE THREAD

**Issue by nilshoerrmann** [beheadedmyway/gity#29]
If a merging conflict occurs, it's not possible to commit changes to solve the issue. It's possible to add the adjusted files but Gity breaks with a message that the current branch is in a conflicted state. Using the command line and `git commit` works.

**Comment by bsneed** [comment]
pushing this to the top of the priority list.  i've been seeing it for awhile, just have been too busy to fix it.

**Comment by bsneed** [comment]
fixed in my fork.
