### ISSUE TITLE
Support for OS X 10.5 

### ISSUE THREAD

**Issue by tylerlane** [beheadedmyway/gity#3]
I am stuck on OS X 10.5 due to software that can not run on 10.6 and would love to see a version of gity that runs on 10.5 as well as 10.6

**Comment by beheadedmyway** [comment]
The behavior of NSOperation, and NSOperationQueue are different from 10.5 and 10.6. It doesn't behave the same way on 10.5 that's why I left support out for it. Feel free to try and get it running, those two classes are really the only reason why I didn't support 10.5.
