### ISSUE TITLE
spaces in local (path) URL result in error when cloning

### ISSUE THREAD

**Issue by Gerk** [beheadedmyway/gity#31]
If there are any spaces when cloning from a local (filesystem) URL (i.e. Volumes/Hard Drive/repo.git) it returns an error about too many arguments on command line.

Workaround:  Manually adding quotes enclosing the URL path fixes this (i.e. '/Volumes/Hard Drive/repo.git' )

Proper Fix:  All repo URL's within the app should probably be quoted by default, it shouldn't hurt anything.

**Comment by bsneed** [comment]
fixed in my branch.
