### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by ferama** [beheadedmyway/gity#38]
Sometimes gity cause very high cpu usage. I think it is when I'm offline and I'm navigating project history. It could be gravatar related issue?

Anyway thanks for this beautiful app ;)

**Comment by bsneed** [comment]
its entirely possible.  i'll have a look, thanks!!

**Comment by bsneed** [comment]
you were 100% correct.  i've fixed the issue, but now the backup image isn't loading.. will continue tomorrow.

**Comment by bsneed** [comment]
fixed in the latest commit.
