### ISSUE TITLE
The ability to checkout from history

### ISSUE THREAD

**Issue by RobertWHurst** [beheadedmyway/gity#7]
I love Gity but I'm really getting tired of dropping to the terminal when I want to checkout or export the working directory from a past commit. It would be really great if it were possible to click on a a commit in history and get the option to checkout that point in history.

**Comment by roefer** [comment]
Where are those links? I only see tar, zip, +tag, and +cherry

**Comment by RobertWHurst** [comment]
Yea you can't checkout, you can only export a point in history. Having a freash look at this I think this needs to be added. I'll have a look at the source, but I'm a javascript and php developer. Not a C developer. None the less I'll have a look.

**Comment by bsneed** [comment]
I added this in my branch if you still care.  Sorry I missed this bug report.  Right click on an item in history and click Checkout.

**Comment by RobertWHurst** [comment]
@bsneed much apreciated. Thanks for sharing your hard work with us.
